name: Repository Size
on: [ push ]
jobs:
    repository_size:
        name: Repository Size
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run: echo "$GITHUB_REF_NAME"
            - run: du -skh --exclude=.git